{% set name = "drug2cell" %}
{% set version = "main" %}
{% set sha256 = "a6353f989f92f05b36972d42795f7f071245d351bf05027dc7e3e4a074ea5bb8" %}
{% set python_min = "3.6" %}  # Specify the minimum supported Python version

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/teichlab/drug2cell/archive/main.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools  # Required build backend
  run:
    - python>={{ python_min }}
    - anndata
    - pandas
    - numpy
    - statsmodels
    - scipy
    - blitzgsea

test:
  commands:
    - drug2cell --help  # Test the CLI functionality
  imports:
    - drug2cell  # Test if the module can be imported

about:
  home: https://github.com/teichlab/drug2cell/
  license: MIT
  license_file: LICENSE
  summary: "A collection of utility functions for gene group activity evaluation in scanpy"





